/*
  # Create Admin User
  
  Creates an initial admin user with username 'ali' and a default password.
  The pin_hash uses the format: salt:hash (generated by expo-crypto)
*/

DO $$
DECLARE
  v_user_exists boolean;
BEGIN
  -- Check if Ali user already exists
  SELECT EXISTS(SELECT 1 FROM app_security WHERE LOWER(user_name) = 'ali') INTO v_user_exists;
  
  IF NOT v_user_exists THEN
    INSERT INTO app_security (
      user_name,
      full_name,
      pin_hash,
      role,
      account_number,
      is_active
    ) VALUES (
      'ali',
      'Ali Admin',
      'e8d6d5eed5b59e12f:6b5a4f3e2d1c0b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c',
      'admin',
      '26000',
      true
    );
  END IF;
END $$;
